"""LLM Provider adapters module supporting Gemini, Mock, and Fallback execution modes."""

from abc import ABC, abstractmethod
import json
import logging
import os
from typing import List, Optional

logger = logging.getLogger(__name__)


class BaseLLMProvider(ABC):
    """Abstract base class defining the contract for LLM integration adapters."""

    @abstractmethod
    def generate_response(self, system_prompt: str, user_content: str) -> str:
        """Generate a textual response from the underlying language model.

        Args:
            system_prompt: System-level instruction directing model behavior.
            user_content: Contextual payload or query input.

        Returns:
            Raw string response generated by the model.
        """
        pass


class GeminiProvider(BaseLLMProvider):
    """Production adapter for Google Gemini API via official google-genai SDK."""

    def __init__(self, api_key: Optional[str] = None, model: str = "gemini-3.6-flash") -> None:
        """Initialize Gemini client with API credentials and model configuration.

        Args:
            api_key: Optional API key. Fallbacks to GEMINI_API_KEY environment variable.
            model: Model identifier string. Defaults to 'gemini-3.6-flash'.

        Raises:
            ValueError: If no valid API key is available.
            ImportError: If 'google-genai' package is not installed.
        """
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "Gemini API key is missing from arguments and GEMINI_API_KEY environment variable."
            )

        try:
            from google import genai

            self.client = genai.Client(api_key=self.api_key)
            self.model_name = model
        except ImportError as err:
            raise ImportError(
                "Package 'google-genai' is not installed. Install via 'pip install google-genai'."
            ) from err

    def generate_response(self, system_prompt: str, user_content: str) -> str:
        """Execute a content generation request against Gemini model enforcing JSON output.

        Args:
            system_prompt: System instructions for agent role persona.
            user_content: Target content and execution payload.

        Returns:
            Raw JSON string response generated by Gemini.
        """
        from google.genai import types

        response = self.client.models.generate_content(
            model=self.model_name,
            contents=user_content,
            config=types.GenerateContentConfig(
                system_instruction=system_prompt,
                temperature=0.1,
                response_mime_type="application/json",
            ),
        )
        return response.text or "{}"


class MockLLMProvider(BaseLLMProvider):
    """Mock provider returning deterministic JSON responses for offline testing and fallbacks."""

    def generate_response(self, system_prompt: str, user_content: str) -> str:
        """Simulate model execution based on system prompt keywords.

        Args:
            system_prompt: System instructions used to determine mock persona.
            user_content: Contextual payload (unused in mock mode).

        Returns:
            Predefined JSON string matching expected schema for hacker or reviewer agents.
        """
        if "Virtual Hacker" in system_prompt or "Red Team" in system_prompt:
            return json.dumps({
                "narrative": "[MOCK FALLBACK] Discovered logical flaws in raw script execution bypassing Security Groups.",
                "exploitability_score": 8,
                "lateral_movement_steps": ["internet", "bastion", "internal-db"],
            })
        elif "Reviewer" in system_prompt or "Blue Team" in system_prompt:
            return json.dumps({
                "executive_summary": "[MOCK FALLBACK] High risk of lateral movement via undocumented script logic.",
                "policy_drift_detected": True,
                "remediations": [{
                    "resource_name": "aws_instance.bastion",
                    "explanation": "Inline scripts bypassed network constraints.",
                    "suggested_code": "# Mock Remediation: Removed inline bash",
                }],
            })
        return "{}"


class FallbackLLMProvider(BaseLLMProvider):
    """Composite provider executing across ordered providers until a successful response is returned."""

    def __init__(self, providers: List[BaseLLMProvider]) -> None:
        """Initialize composite provider with ordered list of fallback targets.

        Args:
            providers: Ordered list of BaseLLMProvider instances to attempt sequentially.
        """
        self.providers = providers

    def generate_response(self, system_prompt: str, user_content: str) -> str:
        """Sequentially attempt response generation across registered providers.

        Args:
            system_prompt: System instructions for agent role persona.
            user_content: Target content and execution payload.

        Returns:
            Response string from first successful provider, or empty JSON string if all fail.
        """
        for provider in self.providers:
            provider_name = provider.__class__.__name__
            try:
                logger.info("Attempting execution with LLM provider: %s", provider_name)
                return provider.generate_response(system_prompt, user_content)
            except Exception as exc:
                logger.warning(
                    "LLM provider %s failed execution: %s. Proceeding to fallback.",
                    provider_name,
                    exc,
                )
                continue
        logger.error("All registered LLM providers failed to respond.")
        return "{}"
